import type { Metadata } from "next";
import { IBM_Plex_Mono, IBM_Plex_Sans_Arabic, Amiri } from "next/font/google";
import "./global.css";
import Header from "@/components/layout/Header";

const IBMPlexSansArabic = IBM_Plex_Sans_Arabic({
  variable: "--font-IBMPlexSansArabic",
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700"],
});
const Amiri_Arabic = Amiri({
  variable: "--font-Amiri",
  subsets: ["latin"],
  weight: ["400", "700"],
});

const IBMPlexMono = IBM_Plex_Mono({
  variable: "--font-IBMPlexMono",
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ar" dir="rtl">
      <body className={`${Amiri_Arabic.variable} ${IBMPlexMono.variable}`}>
        <Header />
        {/* Add top padding to account for fixed header */}
        <main className="pt-20">{children}</main>
      </body>
    </html>
  );
}
