import type { Metadata } from "next";
import { IBM_Plex_Sans_Arabic, Amiri } from "next/font/google";
import "./global.css";
import Header from "@/components/layout/Header";

const IBMPlexSansArabic = IBM_Plex_Sans_Arabic({
  variable: "--font-IBMPlexSansArabic",
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700"],
});

const amiri = Amiri({
  variable: "--font-amiri",
  subsets: ["latin", "arabic"],
  weight: ["400", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ar" dir="rtl">
      <body className={`${IBMPlexSansArabic.variable} ${amiri.variable} `}>
        <Header />
        {/* Add top padding to account for fixed header */}
        <main className="pt-20">{children}</main>

        <footer className="py-10 text-center text-md text-light-span ">
          جميع الحقوق محفوظة لموقع الروضة الإسلامي 1446هـ - 2025م
        </footer>
      </body>
    </html>
  );
}
